import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from './provider';
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";

// Correct font initialization
const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className} bg-[#7b7978] min-h-screen`}>
          <Provider>
            <Navbar /> {/* ✅ Navbar appears on every page */}
            {children}
            <Toaster />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
